# Generated by Django 5.0.3 on 2024-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_answers_quesid_answers_ques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='user_ans',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
